# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_schemas', '0002_schemaquestion_is_response_bool'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaHelpField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('link_name', models.CharField(max_length=50)),
                ('help_text', models.TextField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='schemaresponse',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic_schemas.Schema'),
        ),
    ]
