# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_schemas', '0003_auto_20171204_1001'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SchemaHelpField',
            new_name='SchemaHelpUrl',
        ),
        migrations.AddField(
            model_name='schema',
            name='help_field',
            field=models.ManyToManyField(to='dynamic_schemas.SchemaHelpUrl'),
        ),
    ]
