# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_schemas', '0004_auto_20171204_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemaquestion',
            name='is_editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schema',
            name='help_field',
            field=models.ManyToManyField(to='dynamic_schemas.SchemaHelpUrl', verbose_name='Instruktions felt'),
        ),
        migrations.AlterField(
            model_name='schemaresponse',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
