# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_schemas', '0007_schema_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Hvis du låser kan du ikke ændretabellen i fremtiden.', verbose_name='Lås'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Aktivt'),
        ),
    ]
