# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 09:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dynamic_schemas', '0008_auto_20171212_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemaresponse',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schema',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Hvis du låser kan du ikke ændre tabellen i fremtiden.', verbose_name='Lås'),
        ),
        migrations.AlterField(
            model_name='schemaquestion',
            name='is_editable',
            field=models.BooleanField(default=False, verbose_name='Felt kan ændres'),
        ),
        migrations.AlterField(
            model_name='schemaquestion',
            name='is_response_bool',
            field=models.BooleanField(default=False, verbose_name='Ja/Nej spørgsmål'),
        ),
    ]
