# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 10:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_schemas', '0009_auto_20171215_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='help_field',
            field=models.ManyToManyField(blank=True, to='dynamic_schemas.SchemaHelpUrl', verbose_name='Instruktions felt'),
        ),
        migrations.AlterField(
            model_name='schemaresponse',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
