# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_schemas', '0010_auto_20171221_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemaresponse',
            name='instruction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dynamic_schemas.SchemaHelpUrl'),
        ),
    ]
