# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_schemas', '0013_auto_20180108_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='date_obsolete',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
