# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_schemas', '0015_auto_20180108_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Om tabellen skal vises', verbose_name='Aktivt'),
        ),
    ]
