# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_schemas', '0016_auto_20180108_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='is_obsolete',
            field=models.BooleanField(default=False, help_text='Hvis tabellen er udgået, vil en udgået dato blive sat igennem den her afkrydsning', verbose_name=' Udgået'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Hvis du låser kan du ikke ændre kolonnerne i fremtiden. Du LÅSER kolonnerne.', verbose_name='Lås'),
        ),
    ]
