# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_schemas', '0017_auto_20180108_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemahelpurl',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
