# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_schemas', '0018_auto_20180110_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schemacolumn',
            old_name='is_editable',
            new_name='is_editable_once',
        ),
        migrations.AlterField(
            model_name='schema',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Hvis du låser kan du ikke ændre kolonnerne \n        i fremtiden. Du LÅSER kolonnerne. HVIS DU PRØVER VIL DU FÅ ERROR CODE\n        500', verbose_name='Lås'),
        ),
    ]
