# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_schemas', '0020_auto_20180117_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schemahistory',
            name='new_schema',
        ),
        migrations.AddField(
            model_name='schemahistory',
            name='new_schema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='new', to='dynamic_schemas.Schema'),
        ),
        migrations.RemoveField(
            model_name='schemahistory',
            name='obsolete_schema',
        ),
        migrations.AddField(
            model_name='schemahistory',
            name='obsolete_schema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='obsolete', to='dynamic_schemas.Schema'),
        ),
    ]
