# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_schemas', '0023_auto_20180118_1030'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SchemaHelpUrl',
            new_name='SchemaUrl',
        ),
    ]
