# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-19 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_schemas', '0025_auto_20180119_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='has_ancestor',
            field=models.BooleanField(default=False, help_text='Hvis tabellen har en ældre version af sig, for at fortælle\n        systemet at den skal lave et link der referere tilbage til det skema,\n        skal denne være afkrydset', verbose_name='Har forfædre'),
        ),
    ]
